# Generated by Django 6.0.3 on 2026-03-30 19:48

from django.db import migrations


def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.get_or_create(name='User Administrator')
    Group.objects.get_or_create(name='Executive')
    Group.objects.get_or_create(name='Member')

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_groups'),
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]
