# Generated by Django 6.0.3 on 2026-03-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_status'),
        ('funding', '0005_budgetsection_budgetitem_budgetsheet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_expenses', to='funding.organizationprofile'),
        ),
    ]
