# Generated by Django 6.0.3 on 2026-04-16 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_expense_shared_with'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='shared_with',
        ),
    ]
