# Generated by Django 6.0.2 on 2026-03-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0002_organizationprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationprofile',
            name='supplier_number',
        ),
        migrations.AlterField(
            model_name='organizationprofile',
            name='organization_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
